[ADD] - codingstyle

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -22,17 +22,18 @@ jobs:
         with:
           repository: ''
       - run: |
-          check.sh $(pwd) $(pwd)
-          CODING_STYLE_ERRORS=$(cat $(pwd)/coding-style-reports.log)
+          check.sh "$(pwd)" "$(pwd)"
+          CODING_STYLE_ERRORS=$(< "$(pwd)/coding-style-reports.log")
+          IFS=$'\n'
           for ERRORS in $CODING_STYLE_ERRORS; do
-            array=(`echo $ERRORS | sed 's/:/\n/g'`)
-            echo "::error file=${array[1]#./},title=${array[3]#./} coding style errors detected: ${array[2]#./}::${array[4]#./}"
+              array=($(echo "$ERRORS" | sed 's/:/ /g'))
+              echo "::error file=${array[1]#./},title=${array[3]#./} coding style errors detected: ${array[2]#./}::${array[4]#./}"
           done
-          if [[ -n $CODING_STYLE_ERRORS ]]
-          then
-            exit 1
+          unset IFS
+          if [[ -n $CODING_STYLE_ERRORS ]]; then
+              exit 1
           else
-            echo No coding style errors detected
+              echo "0 coding style errors detected"
           fi
 
   check_program_compilation:
